/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbulanceProvidersRouteImport } from './routes/ambulance-providers'
import { Route as CorporateCompaniesRouteImport } from './routes/corporate-companies'
import { Route as GovernmentAgenciesRouteImport } from './routes/government-agencies'
import { Route as PoliceDepartmentsRouteImport } from './routes/police-departments'
import { Route as SmartCitiesRouteImport } from './routes/smart-cities'
import { Route as TrafficManagementRouteImport } from './routes/traffic-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceProvidersRoute = AmbulanceProvidersRouteImport.update({
  id: '/ambulance-providers',
  path: '/ambulance-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateCompaniesRoute = CorporateCompaniesRouteImport.update({
  id: '/corporate-companies',
  path: '/corporate-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentAgenciesRoute = GovernmentAgenciesRouteImport.update({
  id: '/government-agencies',
  path: '/government-agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliceDepartmentsRoute = PoliceDepartmentsRouteImport.update({
  id: '/police-departments',
  path: '/police-departments',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartCitiesRoute = SmartCitiesRouteImport.update({
  id: '/smart-cities',
  path: '/smart-cities',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficManagementRoute = TrafficManagementRouteImport.update({
  id: '/traffic-management',
  path: '/traffic-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambulance-providers': typeof AmbulanceProvidersRoute
  '/corporate-companies': typeof CorporateCompaniesRoute
  '/government-agencies': typeof GovernmentAgenciesRoute
  '/police-departments': typeof PoliceDepartmentsRoute
  '/smart-cities': typeof SmartCitiesRoute
  '/traffic-management': typeof TrafficManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambulance-providers': typeof AmbulanceProvidersRoute
  '/corporate-companies': typeof CorporateCompaniesRoute
  '/government-agencies': typeof GovernmentAgenciesRoute
  '/police-departments': typeof PoliceDepartmentsRoute
  '/smart-cities': typeof SmartCitiesRoute
  '/traffic-management': typeof TrafficManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambulance-providers': typeof AmbulanceProvidersRoute
  '/corporate-companies': typeof CorporateCompaniesRoute
  '/government-agencies': typeof GovernmentAgenciesRoute
  '/police-departments': typeof PoliceDepartmentsRoute
  '/smart-cities': typeof SmartCitiesRoute
  '/traffic-management': typeof TrafficManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambulance-providers'
    | '/corporate-companies'
    | '/government-agencies'
    | '/police-departments'
    | '/smart-cities'
    | '/traffic-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambulance-providers'
    | '/corporate-companies'
    | '/government-agencies'
    | '/police-departments'
    | '/smart-cities'
    | '/traffic-management'
  id:
    | '__root__'
    | '/'
    | '/ambulance-providers'
    | '/corporate-companies'
    | '/government-agencies'
    | '/police-departments'
    | '/smart-cities'
    | '/traffic-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbulanceProvidersRoute: typeof AmbulanceProvidersRoute
  CorporateCompaniesRoute: typeof CorporateCompaniesRoute
  GovernmentAgenciesRoute: typeof GovernmentAgenciesRoute
  PoliceDepartmentsRoute: typeof PoliceDepartmentsRoute
  SmartCitiesRoute: typeof SmartCitiesRoute
  TrafficManagementRoute: typeof TrafficManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance-providers': {
      id: '/ambulance-providers'
      path: '/ambulance-providers'
      fullPath: '/ambulance-providers'
      preLoaderRoute: typeof AmbulanceProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-companies': {
      id: '/corporate-companies'
      path: '/corporate-companies'
      fullPath: '/corporate-companies'
      preLoaderRoute: typeof CorporateCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-agencies': {
      id: '/government-agencies'
      path: '/government-agencies'
      fullPath: '/government-agencies'
      preLoaderRoute: typeof GovernmentAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/police-departments': {
      id: '/police-departments'
      path: '/police-departments'
      fullPath: '/police-departments'
      preLoaderRoute: typeof PoliceDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-cities': {
      id: '/smart-cities'
      path: '/smart-cities'
      fullPath: '/smart-cities'
      preLoaderRoute: typeof SmartCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic-management': {
      id: '/traffic-management'
      path: '/traffic-management'
      fullPath: '/traffic-management'
      preLoaderRoute: typeof TrafficManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbulanceProvidersRoute: AmbulanceProvidersRoute,
  CorporateCompaniesRoute: CorporateCompaniesRoute,
  GovernmentAgenciesRoute: GovernmentAgenciesRoute,
  PoliceDepartmentsRoute: PoliceDepartmentsRoute,
  SmartCitiesRoute: SmartCitiesRoute,
  TrafficManagementRoute: TrafficManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
